<template>
  <q-layout view="lHh Lpr lFf">
    <q-header elevated>
      <q-toolbar>
        <q-toolbar-title>
          <q-btn to="/">
            <img src="../statics/icons/logo_kabum_.png">
          </q-btn>
        </q-toolbar-title>
        <div>Quasar v{{ $q.version }}</div>
      </q-toolbar>
      <q-card class="bg-primary text-white">
        <q-tabs
          v-model="tab"
          dense
          indicator-color="dark"
          align="justify"
          narrow-indicator
        >
          <q-tab
            name="hardwares"
            label="Hardware"
          />
          <q-tab
            name="smartphones"
            label="SmartPhones"
          />
          <q-tab
            name="perifericos"
            label="Periféricos"
          />
          <q-tab
            name="computadores"
            label="Computadores"
          />
          <q-tab
            name="placasdeVideo"
            label="Placas de Video"
          />
          <q-tab
            name="monitores"
            label="Monitores"
          />
          <q-tab
            name="tecladoEmouse"
            label="Teclado & Mouse"
          />
          <q-tab
            name="gamer"
            label="Gamer"
          />
          <q-tab
            name="homeOffice"
            label="Home Office"
          />
          <q-tab
            name="moreCategorias"
            label="+Categorias"
          />
        </q-tabs>

        <q-separator />

        <q-tab-panels
          v-model="tab"
          animated
          class="bg-primary text-white"
        >
          <q-tab-panel name="hardwares">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>

          <q-tab-panel name="smartphones">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>

          <q-tab-panel name="perifericos">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>
          <q-tab-panel name="computadores">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>

          <q-tab-panel name="placasdeVideo">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>

          <q-tab-panel name="monitores">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>
          <q-tab-panel name="tecladoEmouse">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>

          <q-tab-panel name="homeOffice">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>

          <q-tab-panel name="gamer">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>
          <q-tab-panel name="moreCategorias">
            <q-btn-group spread>
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
              <q-btn
                color="info"
                label="First"
                push
                icon="timeline"
              />
            </q-btn-group>
          </q-tab-panel>
        </q-tab-panels>
      </q-card>
    </q-header>
    <q-page-container>
       <q-carousel
          animated
          v-model="slide"
          arrows
          navigation
          infinite
        >
          <q-carousel-slide
            :name="1"
            img-src="https://cdn.quasar.dev/img/mountains.jpg"
          />
          <q-carousel-slide
            :name="2"
            img-src="https://cdn.quasar.dev/img/parallax1.jpg"
          />
          <q-carousel-slide
            :name="3"
            img-src="https://cdn.quasar.dev/img/parallax2.jpg"
          />
          <q-carousel-slide
            :name="4"
            img-src="https://cdn.quasar.dev/img/quasar.jpg"
          />
        </q-carousel>
        <q-breadcrumbs class="text-brown">
      <template v-slot:separator>
        <q-icon
          size="1.5em"
          name="chevron_right"
          color="primary"
        />
      </template>

      <q-breadcrumbs-el label="Home" icon="home" />
      <q-breadcrumbs-el label="Components" icon="widgets" />
      <q-breadcrumbs-el label="Breadcrumbs" icon="navigation" />
    </q-breadcrumbs>
      <router-view />
    </q-page-container>
  </q-layout>
</template>

<script>

export default {
  name: 'MainLayout',
  data () {
    return {
      tab: '',
      slide: 1
    }
  }
}
</script>
